---
- name: "<r_get_pkg_t_extract> create directory {{ deploy_root }}/install"
  file:
    path: "{{ deploy_root }}/install"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: "<r_get_pkg_t_extract> extract /tmp/{{ package_tarball }} into {{ deploy_root }}/install/"
  unarchive:
    src: "/tmp/{{ package_tarball }}"
    dest: "{{ deploy_root }}/install/"
    #owner:
    #group:
    #mode:
    # If the specified absolute path (file or directory) already
    # exists, this step will *not* be run.
    #creates:
    list_files: yes
  register: unpack_result

- set_fact:
    archive_root: "{{ unpack_result['files'][0] }}"

- name: "<r_get_pkg_t_extract> create a hard link to {{ deploy_root }}/install/{{ package_fullname }}"
  file:
    src: "{{ deploy_root }}/install/{{ archive_root }}"
    dest: "{{ deploy_root }}/install/{{ package_fullname }}"
    #owner:
    #group:
    #mode:
    state: hard

- name: "<r_get_pkg_t_extract> remove {{ deploy_root }}/install/{{ archive_root }}"
  file:
    path: "{{ deploy_root }}/install/{{ archive_root }}"
    state: absent
