---
- name: <r_install_deps_t_common> install dependencies
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
    disable_gpg_check: yes
    #allow_downgrade: yes
  loop: "{{ deps }}"
